### PR TITLE
Using String Enum Constants instead of Strings and some code formatting

### LINKED ISSUE #4: [Feature]: Using StrEnum instead of using string constants in code
### So, what is it about?

Python's [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) class is a way to implement String constants in your code without having to worry about 
1) other developers messing up the constant (like using "North" instead of "NORTH"
2) having to manually type the entire string

Preview of what it can do 
Screenshot 2024-03-22 185036

I would like to fix this issue, so if this looks good , assign me this issue
Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by NishchayKQ**
there are two commits 
the first commit : 44f5224f07b28cb260818b419cf5a9c665a47c01
1) is just formatting the code to match PEP-8 guidelines like blank lines after function definition
2) having imports in the order of standard library -> 3rd party, in alphabetical order

whereas the second commit (0abe004cc7548dfaeda50a263d865875d8c82f60) is Using Str Enum constants instead of Strings

closes #4

### CODE REVIEW

**Comment by Ayushkumarsingh09** [comment]
Yeah this seems to work.

**Comment by NishchayKQ** [comment]
hello, is there something im missing? sorry i opened a pr without getting the issue assigned...

**Comment by Ayushkumarsingh09** [comment]
Yeah, kindly from next time do mention get them assigned first,.

**Comment by NishchayKQ** [comment]
ok! what do i do now?

**Pull request merged**
